### ISSUE TITLE
Version 2.7 breaks compatibility with Visual Studio 2019

### ISSUE THREAD

**Issue by akerfoot** [Unity-Technologies/UnityMixedCallstack#15]
The latest [Version 2.7](https://github.com/Unity-Technologies/UnityMixedCallstack/releases/tag/2.7) which introduces support for VS 2022 cannot be installed on previous versions.

With only 2019 installed, it gives this error:

VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.

**Comment by sambonfire** [comment]
I was unable to install v2.8 as well:

```
2/23/2022 10:25:58 AM - Searching for applicable products...
2/23/2022 10:25:58 AM - Found installed product - Global Location
2/23/2022 10:25:58 AM - Found installed product - Visual Studio Community 2019
2/23/2022 10:25:58 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by UnityAlex** [comment]
v2.8 is for VS2022 and v2.6.1 is fixed for VS19. The reason for the split is there were some breaking changes in VS22 that required dropping support for previous VS versions.
